apiVersion: apps/v1
kind: Deployment
metadata:
  name: bericks
  labels:
    app: bericks
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: bericks
  template:
    metadata:
      labels:
        app: bericks
    spec:
      containers:
      - name: bericks
        image: abhishekf5/ultimate-cicd:4
        ports:
        - containerPort: 8080
